### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/zadanie2#1]
- [x] usun z repozytorium `node_modules` i dodaj ten katalog do `.gitignore`, aby git go ignorowal. Katalog node_modules trzyma zaleznosci, ktore kazdy moze doinstalowac sobie samemu przez `npm install` - nie trzyma sie tego w repo, poniewaz sa to zaleznosci developerskie uzywane tylko podczas tworzenia strony
- [x] popraw obrazek logo (nie wyswietla sie)
- [x] niech obrazki w galerii beda dolaczane z katalogu, w ktorym je trzymasz, a nie z pexels.com

**Comment by renatapro** [comment]
usunęłam node_modules nie tylko z repozytorium ale całkiem z mojego zadania, czyli teraz powinnam jeszcze raz to zainstalować przez npm install ?

- i jeszcze odnośnie .gitignored-założyłam plik tekstowy i wpisałam tam node_modules/, ale nie widziałam żeby on ten plik ignorował

**Comment by zdolny** [comment]
Dobrze, ze usunelas cale `node_modules` i zakomitowalas te zmiane. Tak, jak piszesz, powinnas teraz zainstalowac sobie te zaleznosci jeszcze raz przez `npm install` poniewaz sa one potrzebne do odpalenia taskow grunta - to samo ja robie jak sciagam Twoj projekt.

Problem z `.gitignore`, ktory masz jest taki, ze plik ma zle rozszerzenie `.odt`. Gitignore powinien byc plikiem ukrytym zaczynajacym sie od kropki, bez zadnych dodatkowych rozszerzen.

Dodatkowo:
- [ ] nie wykorzystujesz zminifikowanych obrazkow, ktore wypluwa Ci `imagemin`, tylko zalaczasz oryginalne
- [ ] jesli chodzi o logo to wroc do placehold.it, tylko wpisz wlasciwy url
